### ISSUE TITLE
Feature request: Calendar event tap & onLongPress

### ISSUE THREAD

**Issue by nikopolv** [dlucidone/nativescript-calendar-weekview#1]
To fully utilize this there should be way to allow interaction with the events. Open pop up on long press etc.

While writing this I noticed that onLongPress event crashes the calendar and therefore the whole application. So fix it by providing a way to catch it :)

P.s Awesome work so far! Thank you a lot!

Edit: dived into the code. Needs a bit more time to get to know how these nativescript plugins work, but maybe I can help you in some parts.

**Comment by nikopolv** [comment]
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onEmptyViewLongPress failed

Error: java.lang.AbstractMethodError: abstract method "void com.alamkanak.weekview.WeekView$EmptyViewLongPressListener.onEmptyViewLongPress(java.util.Calendar)"
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.gen.com.alamkanak.weekview.WeekView_EmptyViewLongPressListener.onEmptyViewLongPress(com.alamkanak.weekview.WeekView$EmptyViewLongPressListener.java)
    com.alamkanak.weekview.WeekView$1.onLongPress(WeekView.java:287)
    android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
    android.view.GestureDetector.access$200(GestureDetector.java:40)
    android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:224)
    android.app.ActivityThread.main(ActivityThread.java:5526)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 0, column: -1

StackTrace: 


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
	at com.tns.gen.com.alamkanak.weekview.WeekView_EmptyViewLongPressListener.onEmptyViewLongPress(com.alamkanak.weekview.WeekView$EmptyViewLongPressListener.java)
	at com.alamkanak.weekview.WeekView$1.onLongPress(WeekView.java:287)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
	at android.view.GestureDetector.access$200(GestureDetector.java:40)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.AbstractMethodError: abstract method "void com.alamkanak.weekview.WeekView$EmptyViewLongPressListener.onEmptyViewLongPress(java.util.Calendar)"
	... 17 more


Stacktrace

**Comment by dlucidone** [comment]
@nikopolv Glad you liked. I'm adding more features to it.I'll Update the plugin ASAP.

**Comment by dlucidone** [comment]
Handled the crash event for now and released a new release.
