### ISSUE TITLE
Error - could not find module ui/core/proxy

### ISSUE THREAD

**Issue by idoadse** [dlucidone/nativescript-calendar-weekview#3]
I am developing app in nativescript version 3.1.2.
I tried to use the nativescript-calendar-weekview module and I encounter the following error:

```
JS: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: CalendarWeekView.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_
modules/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:912)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:896)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:888)
JS:     com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.onClick(Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.java:12)
JS:     android.view.View.performClick(View.java:4763)
JS:     android.view.View$PerformClick.run(View.java:19821)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5272)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
JS: TypeError: Could not load view for: CalendarWeekView.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:912)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:896)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:888)
JS:     com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.onClick(Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.java:12)
JS:     android.view.View.performClick(View.java:4763)
JS:     android.view.View$PerformClick.run(View.java:19821)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5272)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
JS:     at Object.getViewClass (file:///data/data/org.nativescript.staccato/files/app/tns_modules/nativescript-angular/element-registry.js:29:15)
JS:     at ViewUtil.createView (file:///data/data/org.nativescript.staccato/files/app/tns_modules/nativescript-angular/view-util.js:122:44)
JS:     at NativeScriptRenderer.createElement (file:///data/data/org.nativescript.staccato/files/app/tns_modules/nativescript-angular/renderer.js:104:30)
JS:     at DebugRenderer2.createElement (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:13284:49)
JS:     at createElement (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:9362:27)
JS:     at createViewNodes (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:12051:44)
JS:     at callViewAction (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:12537:13)
JS:     at execComponentViewsAction (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:12446:13)
JS:     at createViewNodes (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:12120:5)
JS:     at createEmbeddedView (file:///data/data/org.nativescript.staccato/files/app/tns_modu
JS: les/@angular/core/bundles/core.umd.js:11986:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:13213:42)
JS:     at Object.debugCreateEmbeddedView [as createEmbeddedView] (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:12746:12)
JS:     at TemplateRef_.createEmbeddedView (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:10311:38)
JS:     at ViewContainerRef_.createEmbeddedView (file:///data/data/org.nativescript.staccato/files/app/tns_modules/@angular/core/bundles/core.umd.js:10103:52)
JS:     at TabViewItemDirective.ngOnInit (file:///data/data/org.nativescript.staccato/files/app/tns_modules/nativescript-angular/directives/tab-view.js:90:42)

```

I have seen usage of deperecated modules("ui/core/proxy" and "ui/core/dependency-observable").

Is there a chance to fix the module?

Thank you.

**Comment by dlucidone** [comment]
@idoadse the plugin was made with v2.5 so it willn't run with v3. I need some time to update the repo or you can help me in updating it.

**Comment by bzaruk** [comment]
Hey @dlucidone, I will try to help you...but could you please upload the actual typescript files (calendar-weekview.android.js - calendar-weekview.common.js - calendar-weekview.ios.js)

Thanks! :)

**Comment by dlucidone** [comment]
@shabib3 Ok I'll Update the repo

**Comment by bzaruk** [comment]
@dlucidone K thanks! waiting... :)

**Comment by dlucidone** [comment]
@shabib3 I've pushed the typescript files. Create Pull if you'll get this repo working with NS 3.0. I'm closing this issue, Create a new thread if you need any other help

**Comment by Rohanrevanth** [comment]
is this plugin compatible with NS3+ yet?
if so... any update on this pls @dlucidone
